# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [
      (modulesPath + "/installer/scan/not-detected.nix")
      ./hardware/amd_gpu.nix
      ./hardware/audio.nix
      ./hardware/graphics.nix
    ];

  fileSystems."/" =
    {
      device = "os/v1/root";
      fsType = "zfs";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/12CE-A600";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  fileSystems."/srv" =
    {
      device = "os/v1/root/srv";
      fsType = "zfs";
    };

  fileSystems."/root" =
    {
      device = "os/v1/root/root";
      fsType = "zfs";
    };

  fileSystems."/usr" =
    {
      device = "os/v1/root/usr";
      fsType = "zfs";
    };

  fileSystems."/opt" =
    {
      device = "os/v1/root/opt";
      fsType = "zfs";
    };

  fileSystems."/var/lib/libvirt" =
    {
      device = "os/v1/root/var/lib/libvirt";
      fsType = "zfs";
    };

  fileSystems."/lib64" =
    {
      device = "os/v1/root/lib64";
      fsType = "zfs";
    };

  fileSystems."/home/marty" =
    {
      device = "os/v1/root/home/marty";
      fsType = "zfs";
    };

  fileSystems."/var/log" =
    {
      device = "os/v1/root/var/log";
      fsType = "zfs";
    };

  fileSystems."/nix/store" =
    {
      device = "os/v1/root/nix/store";
      fsType = "zfs";
    };

  fileSystems."/etc/nixos" =
    {
      device = "os/v1/root/etc/nixos";
      fsType = "zfs";
    };

  fileSystems."/var/cache" =
    {
      device = "os/v1/root/var/cache";
      fsType = "zfs";
    };

  fileSystems.gvfs.enable = true;

  swapDevices = [ ];

  zramSwap = {
    enable = true;
  };
  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-224106b89100.useDHCP = lib.mkDefault true;
  # networking.interfaces.br-a4ff22dc27fa.useDHCP = lib.mkDefault true;
  # networking.interfaces.br0.useDHCP = lib.mkDefault true;
  # networking.interfaces.docker0.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.virbr0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp100s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
